# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'criar_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.tbox_name = QtWidgets.QLineEdit(Dialog)
        self.tbox_name.setGeometry(QtCore.QRect(150, 50, 113, 20))
        self.tbox_name.setObjectName("tbox_name")
        self.tbox_email = QtWidgets.QLineEdit(Dialog)
        self.tbox_email.setGeometry(QtCore.QRect(150, 80, 113, 20))
        self.tbox_email.setObjectName("tbox_email")
        self.tbox_senha = QtWidgets.QLineEdit(Dialog)
        self.tbox_senha.setGeometry(QtCore.QRect(150, 120, 113, 20))
        self.tbox_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tbox_senha.setObjectName("tbox_senha")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.tbox_confirma_senha = QtWidgets.QLineEdit(Dialog)
        self.tbox_confirma_senha.setGeometry(QtCore.QRect(150, 160, 113, 20))
        self.tbox_confirma_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tbox_confirma_senha.setObjectName("tbox_confirma_senha")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 165, 101, 21))
        self.label_4.setObjectName("label_4")
        self.btn_criar_usuario = QtWidgets.QPushButton(Dialog)
        self.btn_criar_usuario.setGeometry(QtCore.QRect(230, 220, 121, 41))
        self.btn_criar_usuario.setObjectName("btn_criar_usuario")
        self.lbl_status = QtWidgets.QLabel(Dialog)
        self.lbl_status.setGeometry(QtCore.QRect(56, 190, 311, 20))
        self.lbl_status.setObjectName("lbl_status")
        self.btn_voltar = QtWidgets.QPushButton(Dialog)
        self.btn_voltar.setGeometry(QtCore.QRect(30, 220, 121, 41))
        self.btn_voltar.setObjectName("btn_voltar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome: "))
        self.label_2.setText(_translate("Dialog", "Email:"))
        self.label_3.setText(_translate("Dialog", "Senha:"))
        self.label_4.setText(_translate("Dialog", "Confirme a senha:"))
        self.btn_criar_usuario.setText(_translate("Dialog", "Criar usuário"))
        self.lbl_status.setText(_translate("Dialog", "")) # label para atualização de status
        self.btn_voltar.setText(_translate("Dialog", "Voltar"))
        self.lbl_status.setStyleSheet("color: red;")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
