# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gerenciar_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gerenciarUsuarios(object):
    def setupUi(self, gerenciarUsuarios):
        gerenciarUsuarios.setObjectName("gerenciarUsuarios")
        gerenciarUsuarios.resize(561, 353)
        self.lview_usuarios = QtWidgets.QListView(gerenciarUsuarios)
        self.lview_usuarios.setGeometry(QtCore.QRect(50, 30, 191, 271))
        self.lview_usuarios.setObjectName("lview_usuarios")
        self.lbl_selecUsuario = QtWidgets.QLabel(gerenciarUsuarios)
        self.lbl_selecUsuario.setGeometry(QtCore.QRect(50, 10, 111, 20))
        self.lbl_selecUsuario.setObjectName("lbl_selecUsuario")
        self.btn_addUsuario = QtWidgets.QPushButton(gerenciarUsuarios)
        self.btn_addUsuario.setGeometry(QtCore.QRect(280, 30, 141, 31))
        self.btn_addUsuario.setObjectName("btn_addUsuario")
        self.btn_atualizarUsuario = QtWidgets.QPushButton(gerenciarUsuarios)
        self.btn_atualizarUsuario.setGeometry(QtCore.QRect(280, 80, 141, 31))
        self.btn_atualizarUsuario.setObjectName("btn_atualizarUsuario")
        self.btn_removerUsuario = QtWidgets.QPushButton(gerenciarUsuarios)
        self.btn_removerUsuario.setGeometry(QtCore.QRect(280, 130, 141, 31))
        self.btn_removerUsuario.setObjectName("btn_removerUsuario")
        self.btn_voltar = QtWidgets.QPushButton(gerenciarUsuarios)
        self.btn_voltar.setGeometry(QtCore.QRect(450, 300, 75, 23))
        self.btn_voltar.setObjectName("btn_voltar")
        self.lbl_status = QtWidgets.QLabel(gerenciarUsuarios)
        self.lbl_status.setGeometry(QtCore.QRect(20, 310, 421, 31))
        self.lbl_status.setObjectName("lbl_status")

        self.retranslateUi(gerenciarUsuarios)
        QtCore.QMetaObject.connectSlotsByName(gerenciarUsuarios)

    def retranslateUi(self, gerenciarUsuarios):
        _translate = QtCore.QCoreApplication.translate
        gerenciarUsuarios.setWindowTitle(_translate("gerenciarUsuarios", "Dialog"))
        self.lbl_selecUsuario.setText(_translate("gerenciarUsuarios", "Selecione o usuário:"))
        self.btn_addUsuario.setText(_translate("gerenciarUsuarios", "Adicionar Usuário"))
        self.btn_atualizarUsuario.setText(_translate("gerenciarUsuarios", "Atualizar Usuário"))
        self.btn_removerUsuario.setText(_translate("gerenciarUsuarios", "Remover Usuário"))
        self.btn_voltar.setText(_translate("gerenciarUsuarios", "Voltar"))
        self.lbl_status.setText(_translate("gerenciarUsuarios", "<html><head/><body><p><span style=\" color:#ff0000;\"/></p></body></html>"))
        self.lbl_status.setStyleSheet("color: red;")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gerenciarUsuarios = QtWidgets.QDialog()
    ui = Ui_gerenciarUsuarios()
    ui.setupUi(gerenciarUsuarios)
    gerenciarUsuarios.show()
    sys.exit(app.exec_())
