# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(295, 231)
        self.tbox_login_senha = QtWidgets.QLineEdit(Dialog)
        self.tbox_login_senha.setGeometry(QtCore.QRect(81, 61, 151, 20))
        self.tbox_login_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tbox_login_senha.setObjectName("tbox_login_senha")
        self.lbl_esqueci_senha = QtWidgets.QLabel(Dialog)
        self.lbl_esqueci_senha.setGeometry(QtCore.QRect(20, 200, 111, 16))
        self.lbl_esqueci_senha.setObjectName("lbl_esqueci_senha")
        self.lbl_login_senha = QtWidgets.QLabel(Dialog)
        self.lbl_login_senha.setGeometry(QtCore.QRect(31, 55, 61, 31))
        self.lbl_login_senha.setStyleSheet("image: url(:/imagens/password.png);")
        self.lbl_login_senha.setText("")
        self.lbl_login_senha.setObjectName("lbl_login_senha")
        self.tbox_login_email = QtWidgets.QLineEdit(Dialog)
        self.tbox_login_email.setGeometry(QtCore.QRect(81, 25, 151, 20))
        self.tbox_login_email.setObjectName("tbox_login_email")
        self.btn_sair = QtWidgets.QPushButton(Dialog)
        self.btn_sair.setGeometry(QtCore.QRect(81, 105, 71, 31))
        self.btn_sair.setObjectName("btn_sair")
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setGeometry(QtCore.QRect(161, 105, 71, 31))
        self.btn_login.setObjectName("btn_login")
        self.lbl_login_email = QtWidgets.QLabel(Dialog)
        self.lbl_login_email.setGeometry(QtCore.QRect(30, 20, 61, 31))
        self.lbl_login_email.setStyleSheet("image: url(:/imagens/user.png);")
        self.lbl_login_email.setText("")
        self.lbl_login_email.setObjectName("lbl_login_email")
        self.lbl_status_login = QtWidgets.QLabel(Dialog)
        self.lbl_status_login.setGeometry(QtCore.QRect(20, 160, 251, 31))
        self.lbl_status_login.setObjectName("lbl_status_login")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tbox_login_senha.setPlaceholderText(_translate("Dialog", "Digite sua senha"))
        self.lbl_esqueci_senha.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">Esqueci minha senha</span></p></body></html>"))
        self.tbox_login_email.setPlaceholderText(_translate("Dialog", "fulanodetal@phsn.com.br"))
        self.btn_sair.setText(_translate("Dialog", "Sair"))
        self.btn_login.setText(_translate("Dialog", "Entrar"))
        self.lbl_status_login.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_status_login.setStyleSheet("color: red;")
import imagens_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
