# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuPrincipal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_userLogado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_userLogado.setGeometry(QtCore.QRect(580, 320, 211, 20))
        self.lbl_userLogado.setText("")
        self.lbl_userLogado.setObjectName("lbl_userLogado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Gerenciar_Usuarios = QtWidgets.QMenu(self.menubar)
        self.menu_Gerenciar_Usuarios.setObjectName("menu_Gerenciar_Usuarios")
        self.menuGerenciar_Usuarios_2 = QtWidgets.QMenu(self.menu_Gerenciar_Usuarios)
        self.menuGerenciar_Usuarios_2.setObjectName("menuGerenciar_Usuarios_2")
        self.menuImoveis = QtWidgets.QMenu(self.menubar)
        self.menuImoveis.setObjectName("menuImoveis")
        MainWindow.setMenuBar(self.menubar)
        self.actionGerenciar_Usu_rios = QtWidgets.QAction(MainWindow)
        self.actionGerenciar_Usu_rios.setObjectName("actionGerenciar_Usu_rios")
        self.actionCadastrar_usuario = QtWidgets.QAction(MainWindow)
        self.actionCadastrar_usuario.setObjectName("actionCadastrar_usuario")
        self.actionDeletar_Usuario = QtWidgets.QAction(MainWindow)
        self.actionDeletar_Usuario.setObjectName("actionDeletar_Usuario")
        self.actionAlterar_senha = QtWidgets.QAction(MainWindow)
        self.actionAlterar_senha.setObjectName("actionAlterar_senha")
        self.actionBuscar_im_vel = QtWidgets.QAction(MainWindow)
        self.actionBuscar_im_vel.setObjectName("actionBuscar_im_vel")
        self.actionCadastrar_Im_vel = QtWidgets.QAction(MainWindow)
        self.actionCadastrar_Im_vel.setObjectName("actionCadastrar_Im_vel")
        self.menuGerenciar_Usuarios_2.addAction(self.actionCadastrar_usuario)
        self.menuGerenciar_Usuarios_2.addSeparator()
        self.menuGerenciar_Usuarios_2.addAction(self.actionDeletar_Usuario)
        self.menuGerenciar_Usuarios_2.addSeparator()
        self.menuGerenciar_Usuarios_2.addAction(self.actionAlterar_senha)
        self.menuGerenciar_Usuarios_2.addSeparator()
        self.menu_Gerenciar_Usuarios.addSeparator()
        self.menu_Gerenciar_Usuarios.addAction(self.menuGerenciar_Usuarios_2.menuAction())
        self.menubar.addAction(self.menu_Gerenciar_Usuarios.menuAction())
        self.menubar.addAction(self.menuImoveis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_Gerenciar_Usuarios.setTitle(_translate("MainWindow", "Configurações"))
        self.menuGerenciar_Usuarios_2.setTitle(_translate("MainWindow", "Gerenciar Usuários"))
        self.menuImoveis.setTitle(_translate("MainWindow", "Imóveis"))
        self.actionGerenciar_Usu_rios.setText(_translate("MainWindow", "Gerenciar Usuários"))
        self.actionCadastrar_usuario.setText(_translate("MainWindow", "Cadastrar novo usuário"))
        self.actionDeletar_Usuario.setText(_translate("MainWindow", "Deletar Usuário"))
        self.actionAlterar_senha.setText(_translate("MainWindow", "Alterar senha"))
        self.actionBuscar_im_vel.setText(_translate("MainWindow", "Buscar imóvel"))
        self.actionCadastrar_Im_vel.setText(_translate("MainWindow", "Cadastrar Imóvel"))
import imagens_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuPrincipal()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
